Update of README
OSM-Catalan/LangToolsOSM pull request #4
Opened 2022-01-09 19:01 UTC by paunofu

Update of the README instructions

2022-01-10 17:18 UTC, jmaspons requested changes
No sóc partidari del windows però suposo que amb les instruccions qualsevol usuari de Linux tb s'apanyarà :)

2022-01-10 17:18 UTC, jmaspons commented on README.md
> +In the following example you will be able to add all the ```name:ca``` that are missing in the municipality of Alcalalí with the name of the ```name```.
```suggestion
In the following example you will be able to review and add all the ```name:ca``` that are missing in the municipality of Alcalalí with the content of the ```name``` tag which is in catalan.
```

2022-01-10 19:16 UTC, paunofu commented on README.md
> +In the following example you will be able to add all the ```name:ca``` that are missing in the municipality of Alcalalí with the name of the ```name```.
He posat windows perqué jo utilitze windows, encara que si les instruccions són iguals per als dos O.S. es pot eliminar perfectament la menció a windows

2022-01-12 06:59 UTC, Xevib commented
En la meva opinió s'està sobre documentant, no crec que sigui responsabilitat de l'aplicació explicar com obrir un terminal ni com situar-se dins del directori.
Aquesta documentació seria referent a com usar el terminal, ja sigui de Windows o de Linux, de fet si s'elimina aquesta part la documentació de com instal·lar el paquet serà igual per Linux que per Windows

2022-10-22 15:25 UTC, closed without merging